- src/rtnl/constants.rs
- src/rtnl/link/nlas/link_infos.rs
Add support to create XFRM tunnel
This is equivalent to `ip link add name NAME type xfrm if_id NUMBER`
Depends upon: https://github.com/rust-netlink/rtnetlink/pull/6
Signed-off-by: Michael Richardson <mcr@sandelman.ca>
> LinkAddRequest: Allow adding XFRM tunnel with if_id mark

- CHANGELOG
- Cargo.toml
- All public struct and enum are marked as `non_exhaustive`. Please check
https://doc.rust-lang.org/reference/attributes/type_system.html for more
detail. (0b98180)
- Removed the reexport `netlink-packet-core::utils`, please use
`netlink_packet_utils` directly. (a76010a)
- LinkAddRequest: Allow adding XFRM tunnel with if_id mark. (5507d97)
- Bridge: Add support of `IFLA_BR_MCAST_QUERIER_STATE. (3d91fdf)
- LinkAddRequest: Allow adding macvtap on a link. (dabd5dc)
=== Bug fixes
- Fix panics when using iif or oif with ip rule. (dab602e)
> New release 0.14.0

- src/rtnl/constants.rs
Fixed these constants:
* `BRIDGE_VLAN_INFO_PVID`
* `BRIDGE_VLAN_INFO_UNTAGGED`
* `BRIDGE_VLAN_INFO_RANGE_BEGIN`
* `BRIDGE_VLAN_INFO_RANGE_END`
Added these constants:
* `BRIDGE_VLAN_INFO_BRENTRY`
* `BRIDGE_VLAN_INFO_ONLY_OPTS`
Changed to align with expression ` 1 << n` instead of human calculated
value.
> bridge: Fix constants of bridge VLAN

- CHANGELOG
- N/A
- N/A
=== Bug fixes
- Bridge VLAN: Fixed incorrect constants. (6994712)
> New release 0.14.1

- CHANGELOG
- Cargo.toml
- Removed these reexports. (8784586)
* `netlink_packet_route::ErrorMessage`
* `netlink_packet_route::NetlinkBuffer`
* `netlink_packet_route::NetlinkHeader`
* `netlink_packet_route::NetlinkMessage`
* `netlink_packet_route::NetlinkPayload`
* `netlink_packet_route::traits`
* `netlink_packet_route::DecodeError`
- Remove internal fuzz sub-crate. (f2ffa9d)
- N/A
=== Bug fixes
- N/A
> New release 0.15.0

- src/rtnl/constants.rs
- src/rtnl/link/nlas/link_xdp.rs
- src/rtnl/link/nlas/mod.rs
Currently an XDP nlas returns only a Vec<u8>. This commit adds an Xdp enum that breaks down an XDP nlas into attributes. A XdpAttached enum also provides definitions of xdp attachment types.
Parse and emit tests have been added.
I'm unsure if `IFLA_XDP_*` should be `u32` or `u16` but since it was already `u32` I decided to leave it.
> Add XDP nlas structure support

- src/rtnl/tc/constants.rs
- src/rtnl/tc/nlas/filter/matchall.rs
- src/rtnl/tc/nlas/filter/mod.rs
- src/rtnl/tc/nlas/options.rs
This tc filter matches all packets that encounter it.
> Re #21 - Add matchall filter type

- src/rtnl/tc/nlas/action/mod.rs
- src/rtnl/tc/nlas/test.rs
The only place it's used in iproute2 is when setting Parm for an action, and in that spot it is always marked as nested.
> Re #23 - The TCA_ACT_OPTIONS type should also indicate NLM_F_NESTED

- .gitignore
- src/rtnl/constants.rs
- src/rtnl/link/nlas/bond.rs
- src/rtnl/link/nlas/bond_port.rs
- src/rtnl/link/nlas/link_infos.rs
Replaced all `slave` to `port`:
* `InfoBond::ActiveSlave` -> `InfoBond::ActivePort`
* `InfoBond::AllSlavesActive` -> `InfoBond::AllPortsActive`
* `InfoBond::PacketsPerSlave` -> `InfoBond::PacketsPerPort`
* `SlaveState` -> `BondPortState`
* `link_info::Info::SlaveKind` -> `link_info::Info::PortKind`
* `link_info::Info::SlaveData` -> `link_info::Info::PortData`
* `link_info::InfoSlaveData` -> `link_info::InfoPortData`
> [API break] Change slave to port

- CHANGELOG
- Cargo.toml
- Replaced all `slave` to `port`. (bfa1ec3)
* `InfoBond::ActiveSlave` -> `InfoBond::ActivePort`
* `InfoBond::AllSlavesActive` -> `InfoBond::AllPortsActive`
* `InfoBond::PacketsPerSlave` -> `InfoBond::PacketsPerPort`
* `SlaveState` -> `BondPortState`
* `link_infos::Info::SlaveKind` -> `link_info::Info::PortKind`
* `link_infos::Info::SlaveData` -> `link_info::Info::PortData`
* `link_infos::InfoSlaveData` -> `link_info::InfoPortData`
- Add support of bond port settings. (83c9689)
- Add support of TC matchall filter. (d71b961)
- Add egress builder for TcNat type. (62d2411)
- Add the nat action to tc. (c80c678)
- Add XDP nlas structure support. (75ce74c)
=== Bug fixes
- Set `NLM_F_NESTED` for `TCA_ACT_OPTIONS` type. (a93b651)
> New release 0.16.0

- Cargo.toml
- src/rtnl/link/message.rs
- src/rtnl/link/nlas/link_infos.rs
- src/rtnl/link/nlas/tests.rs
- src/rtnl/neighbour/message.rs
- src/rtnl/route/nlas/next_hops.rs
* netlink-packet-core 0.5.0 -> 0.7.0
> Use latest rust-netlink crate

- CHANGELOG
- Cargo.toml
- N/A
- N/A
=== Bug fixes
- Use latest rust-netlink crates. (2eda618)
> New release 0.16.1

- CHANGELOG
- Cargo.toml
- `InfoVlan::EgressQos(Vec<u8>)` changed to
`InfoVlan::EgressQos(Vec<VlanQosMapping>)`. (2d33edb)
- `InfoVlan::IngressQos(Vec<u8>)` changed to
`InfoVlan::IngressQos(Vec<VlanQosMapping>)`. (2d33edb)
- Added rich representation for VLAN QOS mapping. (2d33edb)
- Added MacVlan IFLA_MACVLAN_BC_ options. (640be35)
=== Bug fixes
- N/A
> New release 0.17.0

- src/rtnl/address/message.rs
- src/rtnl/link/header.rs
- src/rtnl/neighbour/header.rs
- src/rtnl/neighbour_table/header.rs
- src/rtnl/nsid/header.rs
- src/rtnl/route/header.rs
- src/rtnl/rule/header.rs
- src/rtnl/tc/message.rs
Partially reverts #11 
It's fine to have this on enums for safety, but the annotation doesn't make sense on transparent pub structs like these. The structs provided here are mirrors of `repr(C)` ABI structs which are not going to trivially change upstream. These are critical for using the library, and marking them `non_exhaustive` makes it impossible for crate users to create these structs immutably.
> Remove non_exhaustive annotation from structs (fixes #25)

- src/rtnl/link/nlas/link_infos.rs
Two things were wrong when attempting to create a vxlan link specifying its src port range:
- we were using native endianness (instead of big endian) to encode the port min / max ranges
- we were not updating the buffer pointer to where we were encoding the min/max values, and thus the "max" was overwriting the "min" value, causing an invalid netlink message.
Unit tests are added.
Fixes: #43 
Depends-on: #42
> Fix vxlan port range

- CHANGELOG
- Cargo.toml
- N/A
- Add support of MACsec interface. (050fd64)
=== Bug fixes
- vxlan: fix port-range attribute marshalling. (55de269)
- vxlan: fix port-range attribute endianness. (ce406b2)
- vxlan: fix port attribute endianness. (927bdd7)
> New release 0.17.1

- examples/new_rule.rs
- src/rtnl/address/nlas/mod.rs
- src/rtnl/address/nlas/test.rs
Changed `rtnl::address::nlas:Nla::Flags(u32)` to `Flags(Inet6AddrFlags)`,
so user of rust-netlink does not need to read kernel code for these flags.
Unit test case included.
> [api_break] ipv6: parse IPv6 address flags

- src/rtnl/address/nlas/mod.rs
- src/rtnl/address/nlas/test.rs
Simply the ipv6 address flags by changing `Nla::Flags(Inet6AddrFlags)`
to `Nla::Flags(Vec<Inet6AddrFlag>)`.
> [api_break] ipv6: Simplify `Nla::Flags(Inet6AddrFlags)`

- .github/workflows/main.yml
- src/rtnl/tc/message.rs
- src/rtnl/tc/nlas/mod.rs
- src/rtnl/tc/nlas/options.rs
- src/rtnl/tc/test.rs
When running `GetQueueDiscipline` against `sfq` scheduler, we will get
DecodeError.
This is because different scheduler has different layout of
`TCA_OPTIONS`.
For `fq_codel`, it is a list of netlink attribute. For kernel code,
`fq_codel_dump()` has `nla_nest_start_noflag(skb, TCA_OPTIONS)`
For `sfq`, it is a single netlink attribute, trying to decode it as
`NlasIterator` will generate DecodeError as expected. For kernel code:
`sfq_dump()` only has `nla_put(skb, TCA_OPTIONS, sizeof(opt), &opt)`.
This patch created `pub(crate) struct VecTcOpt` to handle this
difference correctly.
> tc: Fix DecodeError on sfq scheduler

- src/rtnl/constants.rs
- src/rtnl/link/nlas/link_infos.rs
The patch is introducing HSR interface support. In addition, it is providing the InfoHsr Nla. This Nla is gathering all the IFLA_HSR_ netlink attributes.
Unit test added.
> hsr: support HSR interface

- src/link/attribute.rs
Removed these entries of `LinkAttribute` as they are not used by linux Kernel
6.5.8:
* `LinkAttribute::Pad`
* `LinkAttribute::Weight`
* `LinkAttribute::Priority`
> [API break] link: Remove unused LinkAttribute

- src/rule/flags.rs
The `RuleFlag::DevDetached` is equal to `RuleFlag::IifDetached`, hence
only one of them should be listed in search list of flags.
> rule: Fix crash on RuleFlag of `attempt to subtract with overflow`

- src/lib.rs
- src/message.rs
- src/prefix/attribute.rs
- src/prefix/cache_info.rs
- src/prefix/header.rs
- src/prefix/message.rs
- src/prefix/mod.rs
- src/prefix/tests.rs
I implemented this against an older version of netlink-packet-route (0.7.0) some time ago, and only recently got around to rebasing and upstreaming it. Hopefully the diffs are consistent with the intervening changes to the crate structure and patterns :-).
> prefix: add support for RTM_NEWPREFIX

- src/tc/qdiscs/fq_codel.rs
- src/tc/stats/basic.rs
- src/tc/stats/compat.rs
- src/tc/stats/queue.rs
Adding `Default` macros for a subset of the `non_exhaustive` structs.
Need this in order to write unit tests when using this library. Without `Default` macro, creating this struct is extremely tedious. We cannot use `struct` expression to create them as it results in the below error:
> error[E0639]: cannot create non-exhaustive struct using struct expression
It might be worthwhile to consider if the lib should drop `#[non_exhaustive]` macro altogether because I do not know if the macro is a right choice for a public facing library <sup>[1] [2]</sup>.
[1]: https://doc.rust-lang.org/reference/attributes/type_system.html
[2]: https://github.com/rust-lang/lang-team/issues/143
> Add `Default` macro for non-exhaustive types

- CHANGELOG
- Cargo.toml
- `InfoBridge::RootId` and `InfoBridge::BridgeId` changed. (fb497b3)
- Support bridge bond port information. (faffa52)
- Support RTM_NEWPREFIX. (2a43e1c)
- Add `Default` derive to `TcFqCodelQdStats` and etc. (e21122e)
=== Bug fixes
- N/A
> New release 0.19.0

- src/link/link_info/bridge.rs
- src/link/tests/bridge.rs
The kernel code `net/bridge/br_vlan.c` function
`br_vlan_filter_toggle()` indicate the `IFLA_BR_VLAN_FILTERING` is
holding boolean.
> bridge: Change InfoBridge::VlanFiltering from u8 to bool

- src/link/af_spec/bridge.rs
- src/link/xdp.rs
```
--> src/link/xdp.rs:3:11
|
3   | use std::{convert::TryFrom, mem::size_of, os::fd::RawFd};
|           ^^^^^^^^^^^^^^^^
|
::: /home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/prelude/mod.rs:129:13
|
129 |     pub use core::prelude::rust_2021::*;
|             ------------------------ the item `TryFrom` is already defined here
```
> fix clippy warnings

- src/link/attribute.rs
Hey :)
This is a breaking change; wasn’t sure if it is okay for a <1.0 version, but thought it’s better to try with a patch then opening an issue.
Was also wondering if it’s proper to add doc-comments for these enum variants. If that’s the case I might open a followup PR
---
There are 4 IFLA_* values related to network-namespaces. The following 3 control the `dest_net` of the link:
- `IFLA_NET_NS_PID`      by PID
- `IFLA_NET_NS_FD`       by FD
- `IFLA_TARGET_NETNSID`  by ID    (an alias for `IFLA_IF_NETNSID`)
And the last one controls the `link_net` of the link:
- `IFLA_LINK_NETNSID`    by ID
Currently netlink-packet-route provides 3 enum variants with similar names, which suggest they do the same thing with different input
- `NetNsFd`    => Corresponds to IFLA_NET_NS_FD
- `NetNsPid`   => …
> Rename NetnsId to avoid surprises

- src/link/link_info/vlan.rs
- src/link/xdp.rs
Verify the NlaBuffer has the expected size when parsing the `IFLA_XDP_ATTACHED` and `IFLA_VLAN_QOS_MAPPING` interface NLAs. This prevents a panic opportunity when attempting to parse malformed interface NLAs.
> link: Check buffer length when parsing NLAs

- src/link/link_info/ipvlan.rs
- src/link/link_info/mod.rs
- src/link/mod.rs
- src/link/tests/ipvlan.rs
link: ipvlan: Change mode type from u16 to Enum.
> link: ipvlan: Change mode type from u16 to Enum.

- src/link/link_info/info_data.rs
- src/link/link_info/infos.rs
- src/link/link_info/ipvlan.rs
- src/link/link_info/mod.rs
- src/link/mod.rs
- src/link/tests/ipvtap.rs
- src/link/tests/mod.rs
link: ipvtap: support ipvtap mod. ipvtap is a alias to ipvlan mode.
> link: ipvtap: support ipvtap mod. ipvtap is a alias to ipvlan mode.

- src/link/link_info/bond.rs
- src/link/link_info/mod.rs
- src/link/mod.rs
- src/link/tests/bond.rs
Closes #78
---
@cathay4t Is there an explicit  design decision regarding adding `Other(...)` variants to this kind of enum for forward compatibility?
Saw this behaviour in other enums, such as `AddressScope`, but it also has user-defined values.
> Convert `InfoBond::Mode` into an enum.

- CHANGELOG
- Cargo.toml
- N/A
- Support for tc-actions. (65f699a, 0227234)
- Support `IFLA_VRF_PORT_TABLE` attribute. (abfadc1)
=== Bug fixes
- N/A
> New release 0.20.1

- src/link/attribute.rs
Replace calls to `MapBuffer::new` with `MapBuffer::new_checked`, during link attribute parsing. Without this check, parsing `IFLA_MAP` attributes would panic, if provided with a buffer too short to contain the full `Map` attribute.
> Check Map buffers on creation

- src/link/af_spec/unspec.rs
- src/link/attribute.rs
- src/link/sriov/vf_list.rs
- src/link/sriov/vf_port.rs
- src/neighbour_table/attribute.rs
Replace calls to `NlaBuffer::new` with `NlaBuffer::new_checked`. This ensures that the parsing of individual NLAs is guaranteed to have a valid NlaBuffer (i.e. sufficient bytes to attempt parsing). Without this check, the parsing logic of several attributes would panic if provided with an NlaBuffer that was too short (e.g. length of 1).
One such example is the parsing of `LinkVfPort`, which would have panicked when calling `buf.value()` on line 61 of
src/link/sriov/vf_port.rs.
> Check NLA buffers on creation

- src/route/next_hops.rs
- src/route/tests/route_flags.rs
- src/tc/filters/cls_u32.rs
- src/tc/filters/mod.rs
- src/tc/mod.rs
- src/tc/tests/filter_u32.rs
The first occurs when checking the length of RouteNextHopBuffer. 
If the next-hops length is u16::MAX, adding 8 (the PAYLOAD_OFFSET) to
it would cause integer overflow and lead to a panic. Rather than
switching to `saturating_add`, remove the addition entirely. It was
unnecessary, as the provided length already accounts for the RTA struct.
The second occurs when parsing a TcU32Selector.
`TcU32SelectorBuffer::new_checked` returns an error when the underlying
buffer is not large enough to contain `nkeys`. This avoids an
index-out-of-bounds panic in `TcU32Selector::parse`, when extracting
keys from the underlying buffer.
> Avoid two panics during parsing

- CHANGELOG
- Cargo.toml
- tools/make_release.sh
- `InfoIpVlan::Flags` changed from u16 to `IpVlanFlags`. (321e4d5)
- `AfSpecBridge::Flags` changed from u16 to `BridgeFlag`. (40d090b)
- `InfoBond::ArpValidate` changed from u32 to `BondArpValidate`.(5246712)
- `InfoVxlan::Group` changed from `Vec<u8>` to `Ipv4Addr`. (538e13b)
- `InfoVxlan::Group6` changed from `Vec<u8>` to `Ipv6Addr`. (538e13b)
- `InfoVxlan::Local` changed from `Vec<u8>` to `Ipv4Addr`. (538e13b)
- `InfoVxlan::Local6` changed from `Vec<u8>` to `Ipv6Addr`. (538e13b)
- bridge port: Introduce BridgeFlag, BridgeMode and BridgeVlanTunnelInfo.
(40d090b)
- Add support for geneve links. (7391b19)
=== Bug fixes
- Avoid panic in TcU32Selector parsing. (c49e3ac)
- Avoid panic in RouteNextHopBuffer length checks. (666edbc)
- Check NLA buffers on …
> New release 0.21.0

- src/link/attribute.rs
- src/link/tests/sriov.rs
Using netdevsim driver, it sends empty IFLA_VFINFO_LIST if not configured. When this happens, the payload length is 0. As we are using new_checked() function for NlaBuffer creation, we check that the payload size can allocate the NLA size for that type.
The kernel shouldn't send an empty IFLA_VFINFO_LIST on netdevsim driver when not configured but until that is fixed, this is a proper solution.
It fixes the following error:
```
thread 'main' panicked at links_dump.rs:62:52:
called `Result::unwrap()` on an `Err` value: DecodeError { inner: Failed to parse message with type 16
Caused by:
Decode error occurred: invalid link message }
```
> attribute: fix decoding error on empty IFLA_VFINFO_LIST payload

- CHANGELOG
- Cargo.toml
- Changed `tc::TcActionMirrorOption::Tm` from `Vec<u8>` to `Tcf`. (f3953b8)
- Changed `tc::TcActionNatOption::Tm` from `Vec<u8>` to `Tcf`. (f3953b8)
- Changed `Inet6Stats::out_pkts` to `Inet6Stats::out_requests`. (201d99b)
- tc: Add support of tunnel key. (f5535f3)
- tc: Add flower support. (55e4835)
- ip6 state: Add support of reasm_overlaps and out_pkts. (201d99b)
=== Bug fixes
- Fix error on decoding empty IFLA_VFINFO_LIST. (8ac7c2a)
> New release 0.22.0

- src/address_family_linux.rs
- src/lib.rs
- src/link/af_spec/bridge.rs
- src/link/af_spec/mod.rs
- src/link/attribute.rs
The latest version of the rtnetlink crate cannot compile on Android. The reason is that Android uses the AddressFamily defined in address_family_fallback.rs, while the correct one should be that in address_family_linux.rs. This leads to `AddressFamily::Bridge` used in rtnetlink being undefined on Android.
This patch fixes this by adding necessary `target_os="android"` configs. Since `libc::AF_IB` & `libc::AF_MPLS` are not defined on Android, we still confine branches related to those enums to only linux and fuchsia.
> fix: enable the latest rtnetlink on Android

- src/route/next_hops.rs
- src/route/tests/route_flags.rs
For buffer `[0u8; 8]`, the `RouteNextHopBuffer::attributes()` will panic
on `self.length() - 8` as `0u16 -8` will trigger underflow.
Fixed by raising error when `self.length() < PAYLOAD_OFFSET`.
We consider above all zero buffer as invalid data type instead of
skipping it during pasing is because:
1. The length property is invalid, it should always bigger or equal than 8
because it is the length of payload plus header.
2. The same data will cause error in iproute2 also:
The iproute code `print_rta_multipath()` has:
```c
while (len >= sizeof(*nh)) {
...
len -= NLMSG_ALIGN(nh->rtnh_len);
nh = RTNH_NEXT(nh);
close_json_object();
}
```
The `RTNH_NEXT` is defined as
```c
((struct rtnexthop*)(((char*)(rtnh)) + RTNH_ALIGN((rtnh)->rtnh_len)))
```
It will cause dead loop in iproute2 for `[0u8;8]` …
> route: Fix panic of integer underflow in `RouteNextHopBuffer`

- src/route/attribute.rs
- src/route/lwtunnel.rs
- src/route/mod.rs
- src/route/seg6.rs
- src/route/tests/mod.rs
- src/route/tests/seg6.rs
This commit provide some basic support for Seg6
(https://segment-routing.org/). Support for Inline and Encap more are added. (Further support could be enhanced in the future to support the remaining type, but this is in my opinion a good starting point).
Additional tests are also included by comparing the resulting messages with messaged captured in wireshark.
Note: two expect() are called in the code, but only whenever it is logically impossible to have an exception (checked bounds for IPv6 and parsing of a static IPv6 address)
> Add support for Seg6 encapsulation type

- src/route/via.rs
`From` is already implemented for `Ipv4Addr` and `Ipv6Addr`. This adds the missing `IpAddr` conversion for convenience.
> impl `From<IpAddr>` for `RouteVia`

- CHANGELOG
- Cargo.toml
- tools/make_release.sh
- Changed `InfoBond::PrimaryReselect` from u8 to enum. (7be1634)
- ICMP6: Add support of `ICMP6_MIB_RATELIMITHOST`. (3497a69)
- Support Seg6 encapsulation type. (1a33cd3)
- impl `From<IpAddr>` for `RouteVia`. (7ef6bf6)
=== Bug fixes
- Fix parsing error on empty `IFLA_AF_SPEC`. (5e54549)
- Fix panic of integer underflow in `RouteNextHopBuffer`. (a285aba)
> New release 0.24.0

- src/link/af_spec/in6_addr_gen_mode.rs
- src/link/af_spec/inet6.rs
- src/link/af_spec/mod.rs
- src/link/tests/statistics.rs
- src/link/tests/vrf.rs
> Change AddrGenMode into enum

- .github/workflows/msrv.yml
- CHANGELOG
- Cargo.toml
- Set minimum supported rust version to 1.77. (6bd5418)
- N/A
=== Bug fixes
- Fix compiling error on rust 1.77. (6bd5418)
> New release 0.25.1
